receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ '0.0.0.0:8888' ]

extensions:
  health_check:

processors:
  batch:

exporters:
  logging:
    logLevel: info
  elastic:
    apm_server_url: "http://apm-server:8200"
  jaeger:
    endpoint: jaeger-collector:14250
    insecure: true
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: almaraz-example
    const_labels:
      almaraz: example

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
    metrics:
      receivers: [otlp, prometheus ]
      processors: [batch]
      exporters: [logging, prometheus]