extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
        grpc:
            endpoint: 0.0.0.0:55680

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:
  queued_retry:

exporters:
  logging:
    logLevel: debug

  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: almaraz-example
    const_labels:
      label1: value1

  jaeger:
    endpoint: "0.0.0.0:14250"
    insecure: true


service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch, queued_retry]
      exporters: [logging, jaeger]

    metrics:
      receivers: [opencensus, otlp, prometheus]
      processors: [batch]
      exporters: [logging, prometheus]

  extensions: [health_check, pprof, zpages]

