language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
