spring:
  application:
    name: almaraz-example-prometheus

server:
  port: 8080

logging:
  level:
    root: INFO
    com.elevenpaths: DEBUG
    io.opentelemetry: DEBUG
    io.prometheus: DEBUG
    org.springframework.boot.actuate: INFO
    org.springframework: INFO

almaraz-example:
  base-path: /api
  httpbin-url: http://httpbin.org

management:
  server:
    port: 8090
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    enable-by-default: false
    web:
      exposure:
        include: "health, info, prometheus, metrics"
    #    exclude: "metrics"
  health:
    probes:
      enabled: true