spring:
  application:
    name: almaraz-example

server:
  port: 8080

logging:
  level:
    root: INFO
    com.elevenpaths: DEBUG
    io.opentelemetry: DEBUG

almaraz-example:
  base-path: /api
  httpbin-url: http://httpbin.org
